---
- name: Setup base
  ansible.builtin.import_playbook: playbooks/base.yml

- name: Setup Homebrew
  ansible.builtin.import_playbook: playbooks/brew.yml

- name: Setup Rust
  ansible.builtin.import_playbook: playbooks/rust.yml

- name: Setup Homebrew packages
  ansible.builtin.import_playbook: playbooks/brew-pkgs.yml

- name: Setup aliases
  ansible.builtin.import_playbook: playbooks/alias.yml

- name: Setup git config
  ansible.builtin.import_playbook: playbooks/git.yml

- name: Setup system config
  ansible.builtin.import_playbook: playbooks/config.yml
