---
- hosts: localhost
  name: Install apt packages
  become: true

  tasks:
    - name: "Install system packages"
      ansible.builtin.apt:
        name:
          - jq
          - curl
          - apt-transport-https
          - ca-certificates
          - build-essential
          - gnupg2
          - gnupg
          - vim
          - bat
          - exa
          - google-chrome-stable
          - htop
          - linux-tools-common
          - linux-tools-generic
          - hwloc
          - libssl-dev
          - git
          - nmap
          - zlib1g-dev
          - hyperfine
          - tre-command
          - neofetch
          - bind9-dnsutils
          - wavemon
          - fio
          - iputils-tracepath
          - speedtest-cli
        state: present
